[".tmux/plugins/tmux-yank"]
  type = "archive"
  url = "https://github.com/tmux-plugins/tmux-yank/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".tmux/plugins/tmux-better-mouse-mode"]
  type = "archive"
  url = "https://github.com/NHDaly/tmux-better-mouse-mode/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".tmux/plugins/tmux-thumbs"]
  type = "archive"
  url = "https://github.com/zegervdv/tmux-thumbs/releases/download/0.99.0/tmux-thumbs.x86_64-musl.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".config/bat/themes/One Dark.tmTheme"]
  type = "file"
  url = "https://raw.githubusercontent.com/andresmichel/one-dark-theme/master/One Dark.tmTheme"
  refreshPeriod = "168h"

[".zsh/zsh-history-substring-search.zsh"]
  type = "file"
  url = "https://github.com/zsh-users/zsh-history-substring-search/raw/master/zsh-history-substring-search.zsh"
  refreshPeriod = "168h"
