[".tmux/plugins/tmux-yank"]
  type = "archive"
  url = "https://github.com/tmux-plugins/tmux-yank/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".tmux/plugins/tmux-better-mouse-mode"]
  type = "archive"
  url = "https://github.com/NHDaly/tmux-better-mouse-mode/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".tmux/plugins/tmux-thumbs"]
  type = "archive"
  url = "https://github.com/zegervdv/tmux-thumbs/releases/download/0.99.0/tmux-thumbs.x86_64-musl.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".config/bat/themes/One Dark.tmTheme"]
  type = "file"
  url = "https://raw.githubusercontent.com/andresmichel/one-dark-theme/master/One Dark.tmTheme"
  refreshPeriod = "168h"

[".zsh/zsh-history-substring-search.zsh"]
  type = "file"
  url = "https://github.com/zsh-users/zsh-history-substring-search/raw/master/zsh-history-substring-search.zsh"
  refreshPeriod = "168h"

[".zsh/zsh-autosuggestions.zsh"]
  type = "file"
  url = "https://github.com/zsh-users/zsh-autosuggestions/raw/master/zsh-autosuggestions.zsh"
  refreshPeriod = "168h"

[".zsh/fast-syntax-highlighting"]
  type = "archive"
  url = "https://github.com/zdharma-continuum/fast-syntax-highlighting/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".zsh/zsh-histdb"]
  type = "archive"
  url = "https://github.com/larkery/zsh-histdb/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

[".zsh/fzf-histdb.zsh"]
  type = "file"
  url = "https://github.com/m42e/zsh-histdb-fzf/raw/master/fzf-histdb.zsh"
  refreshPeriod = "168h"

[".zsh/completions/_fd"]
  type = "file"
  url = "https://github.com/sharkdp/fd/raw/master/contrib/completion/_fd"
  refreshPeriod = "168h"

[".zsh/completions/_rg"]
  type = "file"
  url = "https://github.com/BurntSushi/ripgrep/raw/master/complete/_rg"
  refreshPeriod = "168h"
