theme = "tutticolori"

[editor]
line-number = "relative"
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 1

[keys.insert]
C-f = "move_char_right"

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"
