use-grammars = { except = ["gemini"] }

[language-server.pyright-langserver]
command = "pyright-langserver"
args = ["--stdio"]
config = {}

[language-server.ruff-lsp]
command = "ruff-lsp"

[[language]]
name = "python"
roots = ["pyproject.toml"]
formatter = { command = "black", args = ["--quiet", "-"] }
language-servers = ["ruff-lsp", "pyright-langserver"]

[[grammar]]
name = "tcl"
source = { git = "https://github.com/lewis6991/tree-sitter-tcl", rev = "ac8b94b7a89825ddbdd6f8fc0a81c67c065be851" }

[[language]]
name = "tcl"
scope = "source.tcl"
injection-regex = "tcl"
file-types = ["tcl"]
comment-token = "#"
indent = { tab-width = 2, unit = " " }
roots = []

[[language]]
name = 'gotmpl'
file-types = ["tmpl"]

[[grammar]]
name = "hgrc"
source = { git = "https://github.com/zegervdv/tree-sitter-hgrc.git", rev = "d20aa925aa0c56d68215395b9e65dc6003cdcffb" }

[[language]]
name = "hgrc"
scope = "source.hgrc"
injection-regex = "hgrc"
file-types = ["hgrc", ".hgrc"]
comment-token = "#"
indent = { tab-width = 2, unit = " " }
roots = [".hg"]
