use-grammars = { except = ["gemini"] }

[language-server.pyright-langserver]
command = "pyright-langserver"
args = ["--stdio"]
config = {}

[language-server.ruff-lsp]
command = "ruff-lsp"

[[language]]
name = "python"
roots = ["pyproject.toml"]
formatter = { command = "black", args = ["--quiet", "-"] }
language-servers = ["ruff-lsp", "pyright-langserver"]

[[grammar]]
name = "tcl"
source = { git = "https://github.com/lewis6991/tree-sitter-tcl", rev = "ac8b94b7a89825ddbdd6f8fc0a81c67c065be851" }

[[language]]
name = "tcl"
scope = "source.tcl"
injection-regex = "tcl"
file-types = ["tcl"]
comment-token = "#"
indent = { tab-width = 2, unit = " " }
roots = []

[[language]]
name = 'gotmpl'
file-types = ["tmpl"]

[[grammar]]
name = "hgrc"
source = { git = "https://github.com/zegervdv/tree-sitter-hgrc.git", rev = "6bbb8cc15cd489b66244517c3c5bbf4b19fd8ffa" }

[[language]]
name = "hgrc"
scope = "source.hgrc"
injection-regex = "hgrc"
file-types = ["hgrc", ".hgrc"]
comment-token = "#"
indent = { tab-width = 2, unit = " " }
roots = [".hg"]

[[grammar]]
name = "hg-commit"
source = { git = "https://github.com/zegervdv/tree-sitter-hg-commit.git", rev = "310825fccba24d27d9da66597c372f697896a6d3" }

[[language]]
name = "hg-commit"
scope = "source.hg-commit"
injection-regex = "hgrc"
file-types = [{ suffix = "commit.hg.txt" }]
comment-token = "HG:"
indent = { tab-width = 2, unit = " " }
roots = [".hg"]
