[language-server.pyright-langserver]
command = "pyright-langserver"
args = ["--stdio"]
config = {}

[language-server.ruff-lsp]
command = "ruff-lsp"

[[language]]
name = "python"
roots = ["pyproject.toml"]
formatter = { command = "black", args = ["--quiet", "-"] }
language-servers = ["ruff-lsp", "pyright-langserver"]
