name: Environment build test

on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install chezmoi
        run: brew install chezmoi

      - name: Fill template data
        run: |
          touch $HOME/.config/chezmoi/chezmoi.toml
          echo '  [data]' >> $HOME/.config/chezmoi/chezmoi.toml
          echo '    email = "john.doe@example.com"' >> $HOME/.config/chezmoi/chezmoi.toml
          echo '    name = "jdoe"' >> $HOME/.config/chezmoi/chezmoi.toml
          echo '    signingkey = "" ' >> $HOME/.config/chezmoi/chezmoi.toml
          echo '    font_size = "10"' >> $HOME/.config/chezmoi/chezmoi.toml
      - name: check
        run: cat $HOME/.config/chezmoi/chezmoi.toml
      - name: Get repo
        run: chezmoi init -v zegervdv
