name: Environment build test

on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install chezmoi
        run: brew install chezmoi

      - name: Fill template data
        uses: DamianReeves/write-file-action@master
        with:
          path: ~/.config/chezmoi/chezmoi.toml
          contents: |
            [data]
              email = "john.doe@example.com"
              name = "jdoe"
              signingkey = ""
              font_size = "10"

      - name: Get repo
        run: chezmoi init zegervdv
